# Generated by Django 3.2.9 on 2021-11-24 09:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('draw_date', models.DateTimeField()),
                ('policy_id', models.CharField(max_length=250)),
                ('lucky_five', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lucky_five', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=5)),
                ('payment_address', models.CharField(max_length=250)),
                ('bettor', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ticket', models.CharField(blank=True, max_length=250, null=True)),
                ('lottery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lottery.lottery')),
            ],
        ),
    ]
