# Generated by Django 3.2.9 on 2021-11-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
