# Generated by Django 3.2.9 on 2021-11-26 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_bet_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottery',
            old_name='lucky_five',
            new_name='api_response',
        ),
    ]
