# Generated by Django 3.2.9 on 2021-11-26 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_rename_lucky_five_lottery_api_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('tx_id', models.CharField(blank=True, max_length=250, null=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.bet')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.lottery')),
            ],
        ),
    ]
